version: "2"
services:
  backend:
    container_name: backend 
    build: ./backend
    depends_on:
    - frontend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    links: 
      - frontend 
  frontend:
    container_name: frontend
    build: ./frontend
    command: npm start
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
